[tool.poetry]
name = "bot-cloud-handler"
version = "0.1.0"
description = ""
authors = ["Halk Liff <halkliff@pm.me>"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/halkliff/EmaProject/tree/main/packages/bot-cloud-handler"
repository = "https://github.com/halkliff/EmaProject.git"
packages = [{ include = "bot_cloud_handler" }]

[tool.poetry.dependencies]
python = "^3.10"
Telethon = "^1.25.2"
Pillow = "^9.2.0"
hachoir = "^3.1.3"
cryptg = "^0.3.1"
aiohttp = { extras = ["speedups"], version = "^3.8.3" }
flake8 = "^5.0.4"
black = "^22.8.0"
ujson = "^5.5.0"
python-dotenv = "^0.21.0"
pyTelegramBotAPI = "^4.7.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
commitizen = "^2.35.0"

[tool.poetry.scripts]
export-requirements-files = "scripts.export_requirements_files:run"
start = "bot_cloud_handler:start"
# start dev command to run on your own command line to start the bot in watch mode,
# using node's nodemon
# start-dev = "npx nodemon --watch ./bot_cloud_handler --ext py --exec poetry run start"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
