[tool.poetry]
name = "bot-event-dispatcher"
version = "0.1.0"
description = ""
authors = ["Halk Liff <halkliff@pm.me>"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/halkliff/EmaProject/tree/main/packages/bot-event-dispatcher"
repository = "https://github.com/halkliff/EmaProject.git"
packages = [{include = "bot_event_dispatcher"}]

[tool.poetry.dependencies]
python = "^3.12"
flake8 = "7.0.0"
black = "24.2.0"
google-cloud-pubsub="2.19.7"
avro="1.11.3"
cloudevents = "1.10.1"
python-dotenv = "1.0.1"
pyTelegramBotAPI = "4.16.1"
ujson = "5.9.0"
functions-framework = "3.5.0"
icecream = "2.1.3"
types-ujson = "5.9.0.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "3.6.2"
commitizen = "3.16.0"
mypy = "^1.8.0"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = ["telebot.*", "icecream.*", "google.cloud.*"]
ignore_missing_imports = true

[tool.poetry.scripts]
export-requirements-files = "scripts.export_requirements_files:run"
start-dev = "bot_event_dispatcher.long_polling_dispatcher:start"
# start dev command to run on your own command line to start the bot in watch mode,
# using node's nodemon
# start-dev = "npx nodemon --watch ./bot_event_dispatcher --ext py --exec poetry run start"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
